-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 17:44:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `puretherapie`.`KPI`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `puretherapie`.`KPI` (
  `idKPI` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `formula` VARCHAR(255) NULL,
  `tags` VARCHAR(255) NULL,
  PRIMARY KEY (`idKPI`));

CREATE UNIQUE INDEX `kpi_name_UNIQUE` ON `puretherapie`.`KPI` (`name` ASC) VISIBLE;
CREATE INDEX `kpi_tag_idx` ON `puretherapie`.`KPI` (`tags` ASC ) VISIBLE;

GRANT ALL ON TABLE `puretherapie`.`KPI` TO 'PureTherapie_super_admin'@'%';
GRANT UPDATE, SELECT, INSERT, DELETE ON TABLE `puretherapie`.`KPI` TO 'PureTherapie_spring_user'@'%';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
