-- MySQL Script generated by MySQL Workbench
-- Fri Mar 11 10:47:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `puretherapie`.`ReportType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puretherapie`.`ReportType` (
  `idReportType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReportType`));

CREATE UNIQUE INDEX `report_typename_UNIQUE` ON `puretherapie`.`ReportType` (`name` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `puretherapie`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puretherapie`.`Report` (
  `idReport` INT NOT NULL AUTO_INCREMENT,
  `dateBegin` DATE NOT NULL,
  `dateEnd` DATE NOT NULL,
  `file` VARCHAR(255) NULL,
  `idReportType` INT NOT NULL,
  PRIMARY KEY (`idReport`),
  CONSTRAINT `fk_report_report_type`
    FOREIGN KEY (`idReportType`)
    REFERENCES `puretherapie`.`ReportType` (`idReportType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE UNIQUE INDEX `file_UNIQUE` ON `puretherapie`.`Report` (`file` ASC) VISIBLE;

CREATE INDEX `fk_report_report_type_idx` ON `puretherapie`.`Report` (`idReportType` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `puretherapie`.`ReportConfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puretherapie`.`ReportConfiguration` (
  `idReport` INT NOT NULL,
  `idKPI` INT NOT NULL,
  PRIMARY KEY (`idReport`, `idKPI`),
  CONSTRAINT `fk_report_configuration_report`
    FOREIGN KEY (`idReport`)
    REFERENCES `puretherapie`.`Report` (`idReport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_configuration_kpi`
    FOREIGN KEY (`idKPI`)
    REFERENCES `puretherapie`.`KPI` (`idKPI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_report_configuration_kpi_idx` ON `puretherapie`.`ReportConfiguration` (`idKPI` ASC) INVISIBLE;

CREATE INDEX `fk_report_configuration_report_idx` ON `puretherapie`.`ReportConfiguration` (`idReport` ASC) VISIBLE;

CREATE UNIQUE INDEX `uq_report_kpi` ON `puretherapie`.`ReportConfiguration` (`idReport` ASC, `idKPI` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `puretherapie`.`DefaultReportTypeConfiguration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `puretherapie`.`DefaultReportTypeConfiguration` (
  `idReportType` INT NOT NULL,
  `idKPI` INT NOT NULL,
  PRIMARY KEY (`idReportType`, `idKPI`),
  CONSTRAINT `fk_ReportType_has_KPI_ReportType1`
    FOREIGN KEY (`idReportType`)
    REFERENCES `puretherapie`.`ReportType` (`idReportType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReportType_has_KPI_KPI1`
    FOREIGN KEY (`idKPI`)
    REFERENCES `puretherapie`.`KPI` (`idKPI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_default_rt_configuration_kpi_idx` ON `puretherapie`.`DefaultReportTypeConfiguration` (`idKPI` ASC) INVISIBLE;

CREATE INDEX `fk_default_rt_configuration_report_type_idx` ON `puretherapie`.`DefaultReportTypeConfiguration` (`idReportType` ASC) INVISIBLE;

CREATE UNIQUE INDEX `uq_report_type_kpi` ON `puretherapie`.`DefaultReportTypeConfiguration` (`idReportType` ASC, `idKPI` ASC) INVISIBLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `puretherapie`.`Report` TO 'PureTherapie_spring_user'@'%';
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE `puretherapie`.`ReportConfiguration` TO 'PureTherapie_spring_user'@'%';
GRANT INSERT, SELECT, DELETE, UPDATE ON TABLE `puretherapie`.`ReportType` TO 'PureTherapie_spring_user'@'%';
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE `puretherapie`.`DefaultReportTypeConfiguration` TO 'PureTherapie_spring_user'@'%';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
