version: "3.9"
services:
  puretherapie-backend:
    image: puretherapie:latest
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - puretherapie-logs:/logs/
      - puretherapie-properties:/configuration/
volumes:
  puretherapie-logs:
    external: true
  puretherapie-properties:
    external: true